name: GitHub Actions Assignment 1
run-name: ${{ github.actor }} is testing out GitHub Actions.
on: 
    workflow_dispatch:
    push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install nginx
        run: |
          sudo apt update
          sudo apt install -y nginx


      # checkout, build, test, deploy
