name: Run Docker Image using GitHub Actions
run-name: ${{ github.actor }} is attempting to run the docker image.
on: 
    workflow_dispatch:
    push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Build the image
        run: docker build -t hello-flask .
       
      - name: Tag docker image  
        run: docker tag hello-flask-cd libaano/hello-flask-cd:latest
      
      - name: Push docker image to docker desktop
        run: docker push libaano/hello-flask-cd:latest

    